version: '3'

services:
  rei-server:
    build: .
    container_name: rei
    restart: always
    ports:
      - 8001:8001
    volumes:
      - ./:/shared
    environment:
      - READONLY=false
      - SKIP_HIDDEN_FILES=false