version: '3'

services:
  rei:
    build: .
    restart: always
    ports:
      - 8001:8001
    volumes:
      - ./:/shared
    environment:
      - READONLY=false
      - SKIP_HIDDEN_FILES=false
      - USER=admin
      - PASS=admin